define BUBBLE_INPUT
5
5 3 2 4 1
上記を入力をしてください
endef

export BUBBLE_INPUT
bubble_sort:
	echo "$${BUBBLE_INPUT}"
	go run bubble_sort.go


define INSERTION_INPUT
6
5 2 4 6 1 3
上記を入力をしてください
endef

export INSERTION_INPUT
run:
	echo "$${INSERTION_INPUT}"
	go run insertion_sort.go


define SELECTION_INPUT
6
5 6 4 2 1 3
上記を入力をしてください
endef

export SELECTION_INPUT
run:
	echo "$${INPUT}"
	go run selection_sort.go


define SHELL_INPUT
10
4 8 9 1 10 6 2 5 3 7
上記を入力をしてください
endef

export INPSHELL_INPUTUT
run:
	echo "$${SHELL_INPUT}"
	go run shell_sort.go