define LINKED_LIST_INPUT
7
insert 5
insert 2
insert 3
insert 1
insert 3
insert 6
insert 5
上記を入力をしてください
endef

export LINKED_LIST_INPUT
linked_list:
	echo "$${LINKED_LIST_INPUT}"
	go run linked_list.go


define QUEUE_INPUT
5 100
p1 150
p2 80
p3 200
p4 350
p5 20
上記を入力をしてください
endef

export STACK_INPUT
queue:
	echo "$${QUEUE_INPUT}"
	go run queue.go

define STACK_INPUT
1 2 + 3 4 - *
上記を入力をしてください
endef

export STACK_INPUT
run:
	echo "$${STACK_INPUT}"
	go run stack.go